trigger:
  - master

name: BHealthy.CI

pool:
  name: Azure Pipelines
  vmImage: windows-2019

variables:
  Build.ArtifactStagingDirectory: "_BHealthy.CI"
  BuildConfiguration: "Release"
  BuildPlatform: "any cpu"
  Parameters.RestoreBuildProjects: "**/*.csproj"
  Parameters.TestProjects: "**/*[Tt]ests/*.csproj"

steps:
  - task: SonarQubePrepare@4
    displayName: "Prepare SonarQube analysis"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      SonarQube: "SonarQube_Group4"
      projectKey: "group-4"
      projectName: "Group 4"
      extraProperties: |
        sonar.tests=HealthSocialMediaApp/HealthSocialMediaUnitTests/**
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: "$(Parameters.RestoreBuildProjects)"

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: "$(Parameters.RestoreBuildProjects)"
      arguments: "--configuration $(BuildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: "$(Parameters.TestProjects)"
      arguments: "--configuration $(BuildConfiguration)"

  - task: SonarQubeAnalyze@4
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: "Run Code Analysis"

  - task: SonarQubePublish@4
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: "Publish Quality Gate Result"

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: Application Build"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: ARM"
    inputs:
      PathtoPublish: deployment
      ArtifactName: ARM
